// ACTION TYPES
  export const GET_COMMENTS = 'GET_COMMENTS';

  export const REQUEST_COMMENTS       = 'REQUEST_COMMENTS';
  export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
  export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';

  export const REQUEST_ADD_COMMENT = 'REQUEST_ADD_COMMENT';
  export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
  export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';

  export const REQUEST_EDIT_COMMENT = 'REQUEST_EDIT_COMMENT';
  export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
  export const EDIT_COMMENT_FAILURE = 'EDIT_COMMENT_FAILURE';

  export const REQUEST_DELETE_COMMENT = 'REQUEST_DELETE_COMMENT';
  export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
  export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';

  export const REQUEST_VOTE_ON_COMMENT = 'REQUEST_VOTE_ON_COMMENT';
  export const VOTE_ON_COMMENT_SUCCESS = 'VOTE_ON_COMMENT_SUCCESS';
  export const VOTE_ON_COMMENT_FAILURE = 'VOTE_ON_COMMENT_FAILURE';
