// ACTION TYPES
 export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
 export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
 export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';


// export default categories_ActionTypes = {
//  const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
//  const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
//  const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
// }
